"""agregar tabla bitacora

Revision ID: 0f148c0f4957
Revises: c63603119410
Create Date: 2026-04-18 17:03:56.428177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f148c0f4957'
down_revision: Union[str, None] = 'c63603119410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_id'), 'bitacora', ['id'], unique=False)
    op.add_column('mecanicos', sa.Column('taller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mecanicos', 'talleres', ['taller_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mecanicos', type_='foreignkey')
    op.drop_column('mecanicos', 'taller_id')
    op.drop_index(op.f('ix_bitacora_id'), table_name='bitacora')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
