"""agregar_tabla_incidentes

Revision ID: 21595a9aece6
Revises: 0f148c0f4957
Create Date: 2026-04-19 07:53:38.260397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21595a9aece6'
down_revision: Union[str, None] = '0f148c0f4957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'asignado', 'en_camino', 'en_servicio', 'completado', 'cancelado', name='estadoincidente'), nullable=False),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanicos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidentes_id'), 'incidentes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidentes_id'), table_name='incidentes')
    op.drop_table('incidentes')
    # ### end Alembic commands ###
