"""add taller_id to administradores

Revision ID: 26f0c1079801
Revises: 690da5ad74f3
Create Date: 2026-04-28 11:07:09.063646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f0c1079801'
down_revision: Union[str, None] = '690da5ad74f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administradores', sa.Column('taller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'administradores', 'talleres', ['taller_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'administradores', type_='foreignkey')
    op.drop_column('administradores', 'taller_id')
    # ### end Alembic commands ###
