"""reset_inicial

Revision ID: 49ec46f9fb8d
Revises: 
Create Date: 2026-04-29 01:41:45.021686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ec46f9fb8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('talleres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('calificacion_promedio', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talleres_id'), 'talleres', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('superadmin', 'cliente', 'mecanico', 'administrador', name='rolusuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_administradores_id'), 'administradores', ['id'], unique=False)
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_id'), 'bitacora', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('mecanicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('especialidad', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('foto_vehiculo', sa.String(length=500), nullable=True),
    sa.Column('tipo_seguro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_mecanicos_id'), 'mecanicos', ['id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('foto_vehiculo', sa.String(length=500), nullable=True),
    sa.Column('tipo_seguro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'no_disponible', name='estadoincidente'), nullable=False),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('foto_incidente', sa.String(length=500), nullable=True),
    sa.Column('audio_descripcion', sa.String(length=500), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidentes_id'), 'incidentes', ['id'], unique=False)
    op.create_table('asignaciones_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costo_estimado', sa.Float(), nullable=True),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', 'en_camino', 'en_servicio', 'completada', 'cancelada', name='estado_asignacion'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_servicio_id'), 'asignaciones_servicio', ['id'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('foto', 'audio', name='tipo_evidencia'), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('procesado_ia', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_id'), 'evidencias', ['id'], unique=False)
    op.create_table('procesamientos_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'completado', 'error', name='estado_procesamiento'), nullable=False),
    sa.Column('resumen_generado', sa.Text(), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesamientos_ia_id'), 'procesamientos_ia', ['id'], unique=False)
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_actual', sa.String(length=50), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones_servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    op.create_table('servicios_realizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=200), nullable=False),
    sa.Column('descripcion_trabajo', sa.Text(), nullable=False),
    sa.Column('costo_final', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_realizado', sa.DateTime(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones_servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asignacion_id')
    )
    op.create_index(op.f('ix_servicios_realizados_id'), 'servicios_realizados', ['id'], unique=False)
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('puntuacion >= 1 AND puntuacion <= 5', name='ck_puntuacion_rango'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_realizados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id')
    )
    op.create_index(op.f('ix_calificaciones_id'), 'calificaciones', ['id'], unique=False)
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_realizados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id')
    )
    op.create_index(op.f('ix_comisiones_id'), 'comisiones', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', name='estado_pago'), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'pasarela', name='metodo_pago'), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_realizados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_comisiones_id'), table_name='comisiones')
    op.drop_table('comisiones')
    op.drop_index(op.f('ix_calificaciones_id'), table_name='calificaciones')
    op.drop_table('calificaciones')
    op.drop_index(op.f('ix_servicios_realizados_id'), table_name='servicios_realizados')
    op.drop_table('servicios_realizados')
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_procesamientos_ia_id'), table_name='procesamientos_ia')
    op.drop_table('procesamientos_ia')
    op.drop_index(op.f('ix_evidencias_id'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_asignaciones_servicio_id'), table_name='asignaciones_servicio')
    op.drop_table('asignaciones_servicio')
    op.drop_index(op.f('ix_incidentes_id'), table_name='incidentes')
    op.drop_table('incidentes')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_mecanicos_id'), table_name='mecanicos')
    op.drop_table('mecanicos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_bitacora_id'), table_name='bitacora')
    op.drop_table('bitacora')
    op.drop_index(op.f('ix_administradores_id'), table_name='administradores')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_talleres_id'), table_name='talleres')
    op.drop_table('talleres')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
