"""agregar_web_push_subscriptions

Revision ID: 51e73f1cbecd
Revises: df12472a4edc
Create Date: 2026-06-08 11:08:26.777983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e73f1cbecd'
down_revision: Union[str, None] = 'df12472a4edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.String(length=500), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', 'usuario_id', name='uq_endpoint_usuario')
    )
    op.create_index(op.f('ix_web_push_subscriptions_id'), 'web_push_subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_push_subscriptions_id'), table_name='web_push_subscriptions')
    op.drop_table('web_push_subscriptions')
    # ### end Alembic commands ###
