"""agregar_rol_superadmin

Revision ID: 690da5ad74f3
Revises: 99c0ce4d306c
Create Date: 2026-04-24 21:13:14.297098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690da5ad74f3'
down_revision: Union[str, None] = '99c0ce4d306c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procesamientos_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'completado', 'error', name='estado_procesamiento'), nullable=False),
    sa.Column('resumen_generado', sa.Text(), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesamientos_ia_id'), 'procesamientos_ia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procesamientos_ia_id'), table_name='procesamientos_ia')
    op.drop_table('procesamientos_ia')
    # ### end Alembic commands ###
