"""agregar_pagos_y_comisiones

Revision ID: 72334f817b81
Revises: e9b6b57c2378
Create Date: 2026-04-20 15:45:50.500602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72334f817b81'
down_revision: Union[str, None] = 'e9b6b57c2378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_realizados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id')
    )
    op.create_index(op.f('ix_comisiones_id'), 'comisiones', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', name='estado_pago'), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'pasarela', name='metodo_pago'), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_realizados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_comisiones_id'), table_name='comisiones')
    op.drop_table('comisiones')
    # ### end Alembic commands ###
