"""foto_cliente_column

Revision ID: 902cbfe4850d
Revises: 99c0ce4d306c
Create Date: 2026-04-27 01:26:00.414214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902cbfe4850d'
down_revision: Union[str, None] = '99c0ce4d306c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidentes', sa.Column('foto_incidente', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidentes', 'foto_incidente')
    # ### end Alembic commands ###
