"""agregar_evidencias_e_historial_estados

Revision ID: 945590cc2279
Revises: c99dff1c09d9
Create Date: 2026-04-21 14:08:42.395187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945590cc2279'
down_revision: Union[str, None] = 'c99dff1c09d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('foto', 'audio', name='tipo_evidencia'), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('procesado_ia', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_id'), 'evidencias', ['id'], unique=False)
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_actual', sa.String(length=50), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones_servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_evidencias_id'), table_name='evidencias')
    op.drop_table('evidencias')
    # ### end Alembic commands ###
