"""basico_completo_falta_ia_etc

Revision ID: 99c0ce4d306c
Revises: 945590cc2279
Create Date: 2026-04-21 14:28:34.582932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c0ce4d306c'
down_revision: Union[str, None] = '945590cc2279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
