"""rename_table_vehiculos_to_lowercase

Revision ID: c63603119410
Revises: f0e2c8fd8164
Create Date: 2026-04-13 11:23:33.799902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63603119410'
down_revision: Union[str, None] = 'f0e2c8fd8164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('foto_vehiculo', sa.String(length=500), nullable=True),
    sa.Column('tipo_seguro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.drop_index('ix_Vehiculos_id', table_name='Vehiculos')
    op.drop_index('ix_Vehiculos_placa', table_name='Vehiculos')
    op.drop_table('Vehiculos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vehiculos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placa', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('foto_vehiculo', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('tipo_seguro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='Vehiculos_cliente_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Vehiculos_pkey')
    )
    op.create_index('ix_Vehiculos_placa', 'Vehiculos', ['placa'], unique=True)
    op.create_index('ix_Vehiculos_id', 'Vehiculos', ['id'], unique=False)
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
