"""agregar_calificaciones

Revision ID: c99dff1c09d9
Revises: 72334f817b81
Create Date: 2026-04-20 16:04:09.598455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99dff1c09d9'
down_revision: Union[str, None] = '72334f817b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('puntuacion >= 1 AND puntuacion <= 5', name='ck_puntuacion_rango'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_realizados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id')
    )
    op.create_index(op.f('ix_calificaciones_id'), 'calificaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificaciones_id'), table_name='calificaciones')
    op.drop_table('calificaciones')
    # ### end Alembic commands ###
