"""agregar_notificaciones_y_push_token

Revision ID: df12472a4edc
Revises: c5d6e7f8a9b0
Create Date: 2026-06-08 02:10:44.676882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df12472a4edc'
down_revision: Union[str, None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('destinatario_tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('datos_extra', sa.JSON(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.drop_index('ix_asignaciones_tenant_id', table_name='asignaciones_servicio')
    op.create_index(op.f('ix_asignaciones_servicio_tenant_id'), 'asignaciones_servicio', ['tenant_id'], unique=False)
    op.drop_index('ix_servicios_tenant_id', table_name='servicios_realizados')
    op.create_index(op.f('ix_servicios_realizados_tenant_id'), 'servicios_realizados', ['tenant_id'], unique=False)
    op.add_column('usuarios', sa.Column('push_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'push_token')
    op.drop_index(op.f('ix_servicios_realizados_tenant_id'), table_name='servicios_realizados')
    op.create_index('ix_servicios_tenant_id', 'servicios_realizados', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_asignaciones_servicio_tenant_id'), table_name='asignaciones_servicio')
    op.create_index('ix_asignaciones_tenant_id', 'asignaciones_servicio', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
