"""correccion_incidente_quitar_mecanico_simplificar_estados

Revision ID: e43c22fd18ca
Revises: 2e89fb6c8ee4
Create Date: 2026-04-19 22:55:53.036574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43c22fd18ca'
down_revision: Union[str, None] = '2e89fb6c8ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costo_estimado', sa.Float(), nullable=True),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', 'en_camino', 'en_servicio', 'completada', 'cancelada', name='estado_asignacion'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_servicio_id'), 'asignaciones_servicio', ['id'], unique=False)
    op.drop_constraint('incidentes_mecanico_id_fkey', 'incidentes', type_='foreignkey')
    op.drop_column('incidentes', 'mecanico_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidentes', sa.Column('mecanico_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('incidentes_mecanico_id_fkey', 'incidentes', 'mecanicos', ['mecanico_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_asignaciones_servicio_id'), table_name='asignaciones_servicio')
    op.drop_table('asignaciones_servicio')
    # ### end Alembic commands ###
