"""add_audio_descripcion_incidente

Revision ID: e4de9bddafc6
Revises: 902cbfe4850d
Create Date: 2026-04-28 08:30:41.006702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4de9bddafc6'
down_revision: Union[str, None] = '902cbfe4850d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidentes', sa.Column('audio_descripcion', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidentes', 'audio_descripcion')
    # ### end Alembic commands ###
