"""agregar_tabla_servicios_realizados

Revision ID: e9b6b57c2378
Revises: e43c22fd18ca
Create Date: 2026-04-20 00:20:31.284064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b6b57c2378'
down_revision: Union[str, None] = 'e43c22fd18ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios_realizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=200), nullable=False),
    sa.Column('descripcion_trabajo', sa.Text(), nullable=False),
    sa.Column('costo_final', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_realizado', sa.DateTime(), nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones_servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asignacion_id')
    )
    op.create_index(op.f('ix_servicios_realizados_id'), 'servicios_realizados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicios_realizados_id'), table_name='servicios_realizados')
    op.drop_table('servicios_realizados')
    # ### end Alembic commands ###
