"""crear tabalas de usuarios y talleres

Revision ID: f0e2c8fd8164
Revises: 
Create Date: 2026-04-13 11:18:22.010271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e2c8fd8164'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('cliente', 'mecanico', 'administrador', name='rolusuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_administradores_id'), 'administradores', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('mecanicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('foto_vehiculo', sa.String(length=500), nullable=True),
    sa.Column('tipo_seguro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_mecanicos_id'), 'mecanicos', ['id'], unique=False)
    op.create_table('Vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('foto_vehiculo', sa.String(length=500), nullable=True),
    sa.Column('tipo_seguro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Vehiculos_id'), 'Vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_Vehiculos_placa'), 'Vehiculos', ['placa'], unique=True)
    op.create_table('talleres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('calificacion_promedio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talleres_id'), 'talleres', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_talleres_id'), table_name='talleres')
    op.drop_table('talleres')
    op.drop_index(op.f('ix_Vehiculos_placa'), table_name='Vehiculos')
    op.drop_index(op.f('ix_Vehiculos_id'), table_name='Vehiculos')
    op.drop_table('Vehiculos')
    op.drop_index(op.f('ix_mecanicos_id'), table_name='mecanicos')
    op.drop_table('mecanicos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_administradores_id'), table_name='administradores')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
